# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('identity_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
